version: '3.1'

services:
  pg-tasks: # PostgreSQL instance
    image: postgres
    container_name: pg-tasks
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest-tasks
    ports:
      - '5432:5432'
